### ISSUE TITLE
Mob no vs duration

### ISSUE THREAD

**Issue by ghost** [erasmus-without-paper/ewp-wp3-data-model#8]
@kaiqu I think there is some misperception on Mob. No (var) and Duration (unit). Total and average are now mentioned under Mob. No, however I think Mob. No should refer to the number of students, duration to the average or total number of months. The number of students is not strictly required in the template, but from the examples of agreements I came across (quite a few) there is always an indication of the number of students and of the number of months these students can go on an exchange.

e.g. 3 students; 5 months (=average) or 3 students 15 months (=total)

@StefanJahnke does this make sense to you?

**Comment by kaiqu** [comment]
> I think there is some misperception on Mob. No (var) and Duration (unit). Total and average are now mentioned under Mob. No, however I think Mob. No should refer to the number of students, duration to the average or total number of months.

Mob No (short for Mobility Number) does refer to the number of students (or staff), and I understood "total" and "average" to be different variants of the **number** - i.e. you can choose between specifying the total or average number (for a given duration). Are you saying these variants concern the **duration**, i.e. you can choose between specifying the total or average duration (for a given number)?

> The number of students is not strictly required in the template, but from the examples of agreements I came across (quite a few) there is always an indication of the number of students and of the number of months these students can go on an exchange.
> e.g. 3 students; 5 months (=average) or 3 students 15 months (=total)

It seems strange to have a Cooperation Condition not specifying the number ("any number of students for 5 months"). Shouldn't it be mandatory?

Alerting @erasmus-without-paper/wp2 and @erasmus-without-paper/wp3 on these questions.

**Comment by kaiqu** [comment]
>> Total and average are now mentioned under Mob. No, however I think Mob. No should refer to the number of students, duration to the average or total number of months.
> 
> Mob No (short for Mobility Number) does refer to the number of students (or staff), and I understood "total" and "average" to be different variants of the number - i.e. you can choose between specifying the total or average number (for a given duration). Are you saying these variants concern the duration, i.e. you can choose between specifying the total or average duration (for a given number)?

Various pieces of documentation and comments from others support the definition of "total" and "average" to be about Duration, so I will change it in the model, formats and data Dictionary.

>> The number of students is not strictly required in the template, but from the examples of agreements I came across (quite a few) there is always an indication of the number of students and of the number of months these students can go on an exchange.
> e.g. 3 students; 5 months (=average) or 3 students 15 months (=total)
> 
> It seems strange to have a Cooperation Condition not specifying the number ("any number of students for 5 months"). Shouldn't it be mandatory?

I think a clarification is in order:
* In the _data dictionary_, each type of number (studies, training etc) must be optional, since not all of the numbers (i.e. Mobility Types) must be represented. (This is presumably also the case in the template, but I'm not sure in which of the alternate document locations it is located)
* In the _model_, the Mobility Number should be mandatory, since the entity represents a single Mobility Type, and it doesn't make sense to have a Cooperation Condition specifying Duration, EQF Level etc, but not the number.

I close the issue, as I consider it to be answered. If someone has further questions, they can reopen it.
