### ISSUE TITLE
Attributes in Academic term, LOS and LOI

### ISSUE THREAD

**Issue by thomj** [erasmus-without-paper/ewp-wp3-data-model#9]
Some questions concerning the entities “Academic term”, “Learning Opp Spec” and “Learning Opp Instance”:

- Should the entity "Academic term" really belong to a specific organization unit? Is it likely that different organization units within an institution have different start and end dates for their academic terms? If not, would Institution maybe be enough?
- On the other hand, should the entities “Learning Opp Spec” and Learning Opp Instance” perhaps belong to an organization unit instead of only an institution? We felt that this could be needed if a “learning opp spec” would be held by more than one organization unit at the same time (different learning opp instances).

**Comment by kaiqu** [comment]
> * Should the entity "Academic term" really belong to a specific organization unit? Is it likely that different organization units within an institution have different start and end dates for their academic terms? If not, would Institution maybe be enough?

This was discussed earlier, and the conclusion was that some institutions do operate with different Academic Terms. An example of this are "umbrella" institutions with campuses (departments) in different countries.

In most cases, probably, the Academic Terms will be connected to the top level of the hierarchy, but it seems we do need the option to have this vary within an Institution.

> * On the other hand, should the entities “Learning Opp Spec” and Learning Opp Instance” perhaps belong to an organization unit instead of only an institution?

Actually, Learning Opportunity Specification used to belong to Organization Unit, but it was pointed out that there could potentially be more than one LOS with the same LOS Code (but different Unit Id's) for the same Institution - which seems strange. LOS can certainly be _connected_ to Organization Unit, but should _belong_ to (i.e. be partially identified by) it. I will include an optional connection in the next version.

> We felt that this could be needed if a “learning opp spec” would be held by more than one organization unit at the same time (different learning opp instances).

I believe this will be solved in the next version: Since LOI also belongs to (is partially identified by) Academic Term, which in turn belongs to Org Unit (as discussed above), it must include Unit Id in the key - which it does in the next version.

**Comment by wrygiel** [comment]
> LOS can certainly be _connected_ to Organization Unit, but should _belong_ to (i.e. be partially identified by) it

Did you mean "should *not* belong to it"?

**Comment by kaiqu** [comment]
>> LOS can certainly be connected to Organization Unit, but should belong to (i.e. be partially identified by) it
> 
> Did you mean "should _not_ belong to it"?

Sorry - yes, that's what I meant.
